### ISSUE TITLE
Can’t ignore a directory

### ISSUE THREAD

**Issue by jezen** [sebdeckers/grunt-rev#16]
Wanted to do something like this:

```
rev:
  dist:
    files:
      src: [
        "!<%= yeoman.dist %>/images/norev/*"
        "<%= yeoman.dist %>/images/**/*.{png,jpg,jpeg,gif,webp}"
      ]
```

But it doesn’t seem to be working. I want rev to ignore everything in the `norev` directory. I want to ignore those files because usemin fails when trying to process a javascript file optimised by r.js that contains HTML underscore templates in it.

**Comment by brunobatista** [comment]
:+1:

**Comment by alexleone** [comment]
:+1:

**Comment by nicogarcia** [comment]
:+1:

**Comment by zxl9171** [comment]
:+1:

**Comment by ScotSpellman** [comment]
:+1: Thanks!

**Comment by hazelGranger** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
